export interface Product {
  id: string;
  name: string;
  category: string;
  label: string;
  badge: string | null;
  badgeColor: string;
  price: number;
  originalPrice: number | null;
  save: string | null;
  image: string;
  images: string[];
  description: string;
  featured: boolean;
  sku: string;
  tags: string[];
  specs: { label: string; value: string }[];
  keyFeatures: string[];
  whyAkotro: string[];
}

export const ALL_PRODUCTS: Product[] = [
  {
    id: '1', name: 'News Paper Pencil', category: 'RECYCLED PENCIL', label: 'BEST SELLER · NEWSPAPER PENCIL',
    badge: '55% off', badgeColor: '#C0392B', price: 115, originalPrice: 180, save: 'Save ₹65',
    image: '/images/newspaperpencil.avif',
    images: ['/images/newspaperpencil.avif', '/images/brwnpwncil.avif', '/images/84c7b6_a149e7aaeb5847268fb467ce26b25d53~mv2.avif'],
    description: 'Our most beloved pencil. Handcrafted from recycled newspapers, giving waste paper a beautiful second life. Smooth HB lead, earthy texture, perfect everyday pencil.',
    featured: true, sku: 'SKU #PP01',
    tags: ['100% ECO-FRIENDLY', 'WOOD FREE', 'LONG LASTING', 'EASY TO SHARPEN', 'LIGHTWEIGHT', 'PERFECT GRIP'],
    specs: [
      { label: 'Colour', value: 'Newspaper Grey' },
      { label: 'Material', value: 'Recycled Newspaper' },
      { label: 'Point Type', value: 'HB Lead' },
      { label: 'Length', value: '172 mm' },
      { label: 'Diameter', value: '7.2 mm' },
      { label: 'Net Quantity', value: '10 Pencils (Pack of 1)' },
      { label: 'Use For', value: 'Writing, Drawing, Art' },
      { label: 'Made In', value: 'India (Mumbai)' },
    ],
    keyFeatures: [
      'ECO FRIENDLY — Made from 100% Biodegradable Recycled Paper.',
      'BENEFIT — Eco friendly, wood free, polymer free, up-cycled. Easy to sharpen.',
      'PERFECT GRIP — Engineered for comfort during long writing sessions.',
      'LIGHTWEIGHT — At just 7.2mm diameter; it balances perfectly between grip and elegance.',
    ],
    whyAkotro: [
      'PERFECT GIFT — Ideal for students, kids, offices, and businesses who care for the environment.',
      'CREATIVE USE — The best part of recycled paper pencils is that you can create art with it.',
      'SAVE NATURE — Oxygen levels are dropping due to deforestation. Every Akotro pencil is a small act of resistance.',
      'WOMEN-MADE — Handcrafted by women artisans from local Mumbai communities.',
    ],
  },
  {
    id: '2', name: 'Brown Paper Pen', category: 'RECYCLED PEN', label: 'RECYCLED · ECO · NEW ARRIVAL',
    badge: '18% off', badgeColor: '#C0392B', price: 115, originalPrice: 140, save: 'Save ₹25',
    image: '/images/brownpaperpen.avif',
    images: ['/images/brownpaperpen.avif', '/images/pens.avif'],
    description: 'Smooth ballpoint pen crafted from 100% recycled brown paper barrel. Comfortable grip, consistent ink flow, and a warm earthy look that stands apart from plastic pens.',
    featured: false, sku: 'SKU #PP02',
    tags: ['100% ECO-FRIENDLY', 'PLASTIC FREE', 'SMOOTH INK', 'COMFORTABLE GRIP', 'LIGHTWEIGHT', 'REFILLABLE'],
    specs: [
      { label: 'Colour', value: 'Brown' },
      { label: 'Material', value: 'Recycled Brown Paper' },
      { label: 'Point Type', value: 'Bold · 2B Extra Dark Lead' },
      { label: 'Length', value: '172 mm' },
      { label: 'Diameter', value: '7.2 mm' },
      { label: 'Net Quantity', value: '10 Pencils (Pack of 1)' },
      { label: 'Use For', value: 'Writing, Drawing, Art' },
      { label: 'Made In', value: 'India (Mumbai)' },
    ],
    keyFeatures: [
      'ECO FRIENDLY — Made from 100% Biodegradable Recycled Paper.',
      'BENEFIT — Eco friendly, wood free, polymer free, up-cycled. Easy to sharpen.',
      'PERFECT GRIP — Engineered for comfort during long writing sessions.',
      'LIGHTWEIGHT — At just 7.2mm diameter; it balances perfectly.',
    ],
    whyAkotro: [
      'PERFECT GIFT — Ideal for students, kids, offices, and businesses.',
      'CREATIVE USE — Create art with it and also ON it.',
      'SAVE NATURE — Every Akotro pencil is a small act of resistance against global warming.',
      'WOMEN-MADE — Handcrafted by women artisans from local Mumbai communities.',
    ],
  },
  {
    id: '3', name: 'Brown Paper Pencil', category: 'RECYCLED PENCIL', label: 'RECYCLED PENCIL',
    badge: null, badgeColor: '', price: 115, originalPrice: null, save: null,
    image: '/images/brwnpwncil.avif', images: ['/images/brwnpwncil.avif'],
    description: 'Classic HB pencil wrapped in recycled brown kraft paper. Earthy and smooth.',
    featured: false, sku: 'SKU #PP03',
    tags: ['100% ECO-FRIENDLY', 'WOOD FREE', 'EASY TO SHARPEN', 'LIGHTWEIGHT'],
    specs: [{ label: 'Colour', value: 'Brown' }, { label: 'Material', value: 'Recycled Brown Paper' }, { label: 'Length', value: '172 mm' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['ECO FRIENDLY — Made from 100% Biodegradable Recycled Paper.', 'WOOD FREE — No trees harmed.', 'EASY TO SHARPEN — Works with any standard sharpener.'],
    whyAkotro: ['PERFECT GIFT — Ideal for students and offices.', 'WOMEN-MADE — Handcrafted by women artisans from local Mumbai communities.'],
  },
  {
    id: '4', name: 'Black Paper Pencil', category: 'RECYCLED PENCIL', label: 'RECYCLED PENCIL',
    badge: null, badgeColor: '', price: 125, originalPrice: null, save: null,
    image: '/images/blackpaperpencil.avif', images: ['/images/blackpaperpencil.avif'],
    description: 'Bold and striking. Made from recycled black paper with smooth HB lead.',
    featured: false, sku: 'SKU #PP04',
    tags: ['100% ECO-FRIENDLY', 'WOOD FREE', 'SMOOTH HB LEAD', 'UNIQUE LOOK'],
    specs: [{ label: 'Colour', value: 'Black' }, { label: 'Material', value: 'Recycled Black Paper' }, { label: 'Length', value: '172 mm' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['ECO FRIENDLY — Made from 100% Biodegradable Recycled Paper.', 'STRIKING LOOK — Unique black exterior.', 'SMOOTH LEAD — Perfect for writing and sketching.'],
    whyAkotro: ['PERFECT GIFT — Stands out from the crowd.', 'WOMEN-MADE — Handcrafted by women artisans from local Mumbai communities.'],
  },
  {
    id: '5', name: 'White Paper Pencil', category: 'RECYCLED PENCIL', label: 'RECYCLED PENCIL',
    badge: null, badgeColor: '', price: 108, originalPrice: null, save: null,
    image: '/images/whitepaperpencil.avif', images: ['/images/whitepaperpencil.avif'],
    description: 'Clean minimalist pencil made from recycled white paper. Soft HB lead.',
    featured: false, sku: 'SKU #PP05',
    tags: ['100% ECO-FRIENDLY', 'WOOD FREE', 'MINIMALIST', 'SOFT LEAD'],
    specs: [{ label: 'Colour', value: 'White' }, { label: 'Material', value: 'Recycled White Paper' }, { label: 'Length', value: '172 mm' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['ECO FRIENDLY — Recycled white paper construction.', 'MINIMALIST DESIGN — Clean and elegant.', 'SOFT HB LEAD — Great for everyday writing.'],
    whyAkotro: ['PERFECT GIFT — Clean aesthetic loved by all.', 'WOMEN-MADE — Handcrafted by women artisans from local Mumbai communities.'],
  },
  {
    id: '6', name: 'Color Lead Color Paper Pencil', category: 'LIMITED EDITION PENCIL', label: 'LIMITED',
    badge: '40% off', badgeColor: '#E67E22', price: 160, originalPrice: 220, save: 'Save ₹60',
    image: '/images/colourleadpaperpencil.avif', images: ['/images/colourleadpaperpencil.avif', '/images/colourpaperpencil.avif'],
    description: 'Vibrant color-lead pencil wrapped in colorful recycled paper. Limited edition.',
    featured: true, sku: 'SKU #PP06',
    tags: ['LIMITED EDITION', 'COLOR LEADS', 'ECO-FRIENDLY', 'ARTIST FAVOURITE'],
    specs: [{ label: 'Colour', value: 'Multi-Color' }, { label: 'Material', value: 'Recycled Colored Paper' }, { label: 'Length', value: '172 mm' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['LIMITED EDITION — Rare and collectible.', 'COLOR LEADS — Vivid, smooth color output.', 'ECO WRAP — Recycled paper exterior.'],
    whyAkotro: ['PERFECT GIFT — Wow factor guaranteed.', 'CREATIVE USE — Perfect for artists and kids.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '7', name: 'Color Lead News Paper Pencil', category: 'LIMITED EDITION PENCIL', label: 'LIMITED EDITION',
    badge: '40% off', badgeColor: '#E67E22', price: 125, originalPrice: 180, save: 'Save ₹55',
    image: '/images/84c7b6_a149e7aaeb5847268fb467ce26b25d53~mv2.avif',
    images: ['/images/84c7b6_a149e7aaeb5847268fb467ce26b25d53~mv2.avif', '/images/newspaperpencil.avif'],
    description: 'Color lead in a recycled newspaper shell. Earthy outside, vibrant inside.',
    featured: false, sku: 'SKU #PP07',
    tags: ['LIMITED EDITION', 'COLOR LEADS', 'NEWSPAPER WRAP', 'ECO-FRIENDLY'],
    specs: [{ label: 'Colour', value: 'Multi-Color Lead' }, { label: 'Material', value: 'Recycled Newspaper' }, { label: 'Length', value: '172 mm' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['NEWSPAPER WRAP — Unique earthy exterior.', 'COLOR LEADS — Vibrant inside.', 'ECO FRIENDLY — 100% recycled.'],
    whyAkotro: ['CREATIVE USE — Art on the outside and inside.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '8', name: 'Color Paper Pencil', category: 'LIMITED EDITION PENCIL', label: 'LIMITED EDITION PENCIL',
    badge: '35% off', badgeColor: '#C0392B', price: 129, originalPrice: 199, save: 'Save ₹70',
    image: '/images/colourpaperpencil.avif', images: ['/images/colourpaperpencil.avif', '/images/colourpaperpencil2.avif'],
    description: 'Multi-color recycled paper pencil that writes smooth and looks stunning.',
    featured: false, sku: 'SKU #PP08',
    tags: ['ECO-FRIENDLY', 'COLORFUL', 'SMOOTH WRITE', 'KIDS FAVOURITE'],
    specs: [{ label: 'Colour', value: 'Multi-Color' }, { label: 'Material', value: 'Recycled Colored Paper' }, { label: 'Length', value: '172 mm' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['COLORFUL DESIGN — Eye-catching look.', 'SMOOTH WRITE — HB lead glides effortlessly.', 'ECO FRIENDLY — No plastic.'],
    whyAkotro: ['PERFECT GIFT — Kids and artists love it.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '9', name: 'Plantable Brown Paper Pencil', category: 'PLANTABLE PENCIL', label: 'PLANTABLE PENCIL',
    badge: null, badgeColor: '', price: 150, originalPrice: 250, save: 'Save ₹100',
    image: '/images/brwnpwncil.avif', images: ['/images/brwnpwncil.avif'],
    description: 'Write with it. Plant it. Watch it grow. Seed-embedded brown paper pencil.',
    featured: false, sku: 'SKU #PP09',
    tags: ['PLANTABLE', 'SEED EMBEDDED', 'ECO-FRIENDLY', 'ZERO WASTE'],
    specs: [{ label: 'Colour', value: 'Brown' }, { label: 'Material', value: 'Recycled Paper + Seeds' }, { label: 'Seed Type', value: 'Herbs / Flowers' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['PLANTABLE — Contains embedded seeds.', 'ZERO WASTE — No stub left behind.', 'ECO FRIENDLY — 100% biodegradable.'],
    whyAkotro: ['UNIQUE GIFT — Write it, plant it.', 'SAVE NATURE — Grow plants, not waste.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '10', name: 'Plantable Brown Paper Pen', category: 'PLANTABLE PEN', label: 'PLANTABLE PEN',
    badge: null, badgeColor: '', price: 115, originalPrice: 245, save: 'Save ₹130',
    image: '/images/brownpaperpen.avif', images: ['/images/brownpaperpen.avif'],
    description: 'A pen that becomes a plant. Seed capsule at the end grows herbs or flowers.',
    featured: false, sku: 'SKU #PP10',
    tags: ['PLANTABLE', 'SEED CAPSULE', 'ECO-FRIENDLY', 'ZERO PLASTIC'],
    specs: [{ label: 'Colour', value: 'Brown' }, { label: 'Material', value: 'Recycled Paper + Seeds' }, { label: 'Seed Type', value: 'Herbs / Flowers' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['SEED CAPSULE — Grows herbs or flowers when planted.', 'ZERO PLASTIC — Completely plastic free.', 'SMOOTH INK — Consistent ballpoint flow.'],
    whyAkotro: ['PERFECT GIFT — Unique and meaningful.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '11', name: 'Eco Paper Pen', category: 'ECO PEN', label: 'ECO PEN',
    badge: null, badgeColor: '', price: 115, originalPrice: null, save: null,
    image: '/images/pens.avif', images: ['/images/pens.avif'],
    description: 'Smooth ballpoint eco pen made from 100% recycled paper. Zero plastic.',
    featured: false, sku: 'SKU #PP11',
    tags: ['ECO-FRIENDLY', 'ZERO PLASTIC', 'SMOOTH INK', 'DURABLE'],
    specs: [{ label: 'Material', value: 'Recycled Paper' }, { label: 'Ink Type', value: 'Ballpoint' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['ZERO PLASTIC — No plastic at all.', 'SMOOTH INK — Writes clean every time.', 'ECO FRIENDLY — 100% recycled paper body.'],
    whyAkotro: ['EVERYDAY USE — Reliable and eco.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '12', name: 'Plantable Eco Paper Pen', category: 'PLANTABLE ECO PEN', label: 'PLANTABLE ECO PEN',
    badge: null, badgeColor: '', price: 116, originalPrice: null, save: null,
    image: '/images/pens.avif', images: ['/images/pens.avif'],
    description: 'Eco pen with embedded seeds. Write today, plant tomorrow.',
    featured: false, sku: 'SKU #PP12',
    tags: ['PLANTABLE', 'SEED EMBEDDED', 'ECO-FRIENDLY', 'ZERO PLASTIC'],
    specs: [{ label: 'Material', value: 'Recycled Paper + Seeds' }, { label: 'Seed Type', value: 'Herbs / Flowers' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['PLANTABLE — Write and then plant.', 'ECO PEN — No plastic body.', 'SEED CAPSULE — Grows something green.'],
    whyAkotro: ['UNIQUE GIFT — Unlike any other pen.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '13', name: 'Plantable News Paper Pencil', category: 'PLANTABLE PENCIL', label: 'PLANTABLE PENCIL',
    badge: null, badgeColor: '', price: 116, originalPrice: null, save: null,
    image: '/images/plantalblenewspaperpencil.avif', images: ['/images/plantalblenewspaperpencil.avif'],
    description: 'Newspaper pencil with seed capsule. Writes and grows.',
    featured: false, sku: 'SKU #PP13',
    tags: ['PLANTABLE', 'NEWSPAPER WRAP', 'SEED EMBEDDED', 'ECO-FRIENDLY'],
    specs: [{ label: 'Material', value: 'Recycled Newspaper + Seeds' }, { label: 'Seed Type', value: 'Herbs' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['NEWSPAPER WRAP — Rustic look.', 'PLANTABLE — Embedded with seeds.', 'ZERO WASTE — Fully biodegradable.'],
    whyAkotro: ['PERFECT GIFT — One that keeps giving.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '14', name: 'Plantable Black Paper Pencil', category: 'PLANTABLE PENCIL', label: 'PLANTABLE PENCIL',
    badge: null, badgeColor: '', price: 140, originalPrice: null, save: null,
    image: '/images/plantableblackpaperpencil.avif', images: ['/images/plantableblackpaperpencil.avif'],
    description: 'Dark, bold plantable pencil. Write it, plant it, grow something beautiful.',
    featured: false, sku: 'SKU #PP14',
    tags: ['PLANTABLE', 'BLACK PAPER', 'ECO-FRIENDLY', 'ZERO WASTE'],
    specs: [{ label: 'Colour', value: 'Black' }, { label: 'Material', value: 'Recycled Black Paper + Seeds' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['BOLD LOOK — Striking black exterior.', 'PLANTABLE — Embedded with seeds.', 'ECO FRIENDLY — 100% biodegradable.'],
    whyAkotro: ['UNIQUE GIFT — Dark and eco.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '15', name: 'Plantable Color Paper Pencil', category: 'PLANTABLE PENCIL', label: 'PLANTABLE PENCIL',
    badge: null, badgeColor: '', price: 140, originalPrice: null, save: null,
    image: '/images/colourpaperpencil2.avif', images: ['/images/colourpaperpencil2.avif'],
    description: 'Colorful plantable pencil packed with seeds. Art meets nature.',
    featured: false, sku: 'SKU #PP15',
    tags: ['PLANTABLE', 'COLORFUL', 'SEED EMBEDDED', 'ECO-FRIENDLY'],
    specs: [{ label: 'Colour', value: 'Multi-Color' }, { label: 'Material', value: 'Recycled Colored Paper + Seeds' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['COLORFUL — Bright and fun.', 'PLANTABLE — Contains embedded seeds.', 'ECO FRIENDLY — Zero waste.'],
    whyAkotro: ['PERFECT GIFT — Kids will love it.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '16', name: 'Plantable White Paper Pencil', category: 'PLANTABLE PENCIL', label: 'PLANTABLE PENCIL',
    badge: null, badgeColor: '', price: 120, originalPrice: null, save: null,
    image: '/images/plantablewhitepaperpencil.avif', images: ['/images/plantablewhitepaperpencil.avif'],
    description: 'Minimal white plantable pencil. Clean design, green soul.',
    featured: false, sku: 'SKU #PP16',
    tags: ['PLANTABLE', 'WHITE PAPER', 'MINIMALIST', 'ECO-FRIENDLY'],
    specs: [{ label: 'Colour', value: 'White' }, { label: 'Material', value: 'Recycled White Paper + Seeds' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['MINIMALIST — Clean white design.', 'PLANTABLE — Seeds inside.', 'ECO FRIENDLY — 100% biodegradable.'],
    whyAkotro: ['ELEGANT GIFT — Simple and meaningful.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '17', name: 'Color Lead Color Paper Pencil', category: 'COLOUR LEAD PENCIL', label: 'COLOUR LEAD PENCIL',
    badge: null, badgeColor: '', price: 125, originalPrice: null, save: null,
    image: '/images/colourleadpaperpencil.avif', images: ['/images/colourleadpaperpencil.avif'],
    description: 'Multi-hued color lead pencil in a recycled paper wrap. Artist favourite.',
    featured: false, sku: 'SKU #PP17',
    tags: ['COLOR LEADS', 'ECO-FRIENDLY', 'ARTIST FAVOURITE', 'RECYCLED WRAP'],
    specs: [{ label: 'Colour', value: 'Multi-Color Leads' }, { label: 'Material', value: 'Recycled Paper' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['COLOR LEADS — Vivid, smooth strokes.', 'ECO WRAP — Recycled paper shell.', 'ARTIST GRADE — Loved by illustrators.'],
    whyAkotro: ['CREATIVE USE — Perfect for art.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
  {
    id: '18', name: 'Plantable Color Lead Paper Pencil', category: 'PLANTABLE · LIMITED', label: 'PLANTABLE · LIMITED',
    badge: null, badgeColor: '', price: 140, originalPrice: null, save: null,
    image: '/images/plantableleadpaperpencil.avif', images: ['/images/plantableleadpaperpencil.avif'],
    description: 'Limited plantable pencil with color leads. Rare, beautiful, sustainable.',
    featured: true, sku: 'SKU #PP18',
    tags: ['LIMITED EDITION', 'PLANTABLE', 'COLOR LEADS', 'ECO-FRIENDLY'],
    specs: [{ label: 'Colour', value: 'Multi-Color' }, { label: 'Material', value: 'Recycled Paper + Seeds' }, { label: 'Made In', value: 'India (Mumbai)' }],
    keyFeatures: ['LIMITED EDITION — Rare collectible.', 'PLANTABLE — Seeds embedded.', 'COLOR LEADS — Vivid and bright.'],
    whyAkotro: ['PERFECT GIFT — Rare and meaningful.', 'CREATIVE USE — Art and nature combined.', 'WOMEN-MADE — Handcrafted by women artisans.'],
  },
];
